import {useEffect,useMemo,useState} from 'react';import {Plus,Trash2,Edit3,Star,ExternalLink,Download,FileText,CheckCircle2,Circle} from 'lucide-react';import {api} from '../services/api';import {Button,Modal,Field,Textarea,Select,SearchBox,Empty,Confirm,Spinner,toast} from '../components/ui';
const cfg={plans:{title:'PlanIt',sub:'Turn goals into clear, trackable steps.',label:'plan',endpoint:'/plans'},ideas:{title:'IdeaLab',sub:'Capture ideas and develop them into something real.',label:'idea',endpoint:'/ideas'},links:{title:'LinkSpace',sub:'Your personal library of useful websites and resources.',label:'link',endpoint:'/links'},documents:{title:'Digital Locker',sub:'Securely organize your personal files and documents.',label:'document',endpoint:'/documents'}};
export default function ResourcePage({type}){const c=cfg[type], [items,setItems]=useState([]),[q,setQ]=useState(''),[open,setOpen]=useState(false),[edit,setEdit]=useState(null),[del,setDel]=useState(null),[loading,setLoading]=useState(true);const load=()=>{setLoading(true);api.get(c.endpoint,{params:q?{q}:undefined}).then(r=>setItems(r.data)).catch(e=>toast.error(e.response?.data?.message||'Load failed')).finally(()=>setLoading(false))};useEffect(load,[q]);useEffect(()=>{const h=()=>load();window.addEventListener('pf-resource-refresh',h);return()=>window.removeEventListener('pf-resource-refresh',h)},[]);const save=async data=>{try{if(edit)await api.put(`${c.endpoint}/${edit._id}`,data);else await api.post(c.endpoint,data);toast.success(edit?'Updated':'Created');setOpen(false);setEdit(null);load()}catch(e){toast.error(e.response?.data?.message||'Save failed')}};const remove=async()=>{try{await api.delete(`${c.endpoint}/${del._id}`);toast.success('Deleted');setDel(null);load()}catch(e){toast.error('Delete failed')}};return <><div className="page-head"><div><span className="eyebrow">MODULE</span><h1>{c.title}</h1><p>{c.sub}</p></div><Button onClick={()=>{setEdit(null);setOpen(true)}}><Plus size={17}/> New {c.label}</Button></div><div className="toolbar"><SearchBox value={q} onChange={setQ}/></div>{loading?<div className="center"><Spinner/></div>:!items.length?<Empty title={`No ${c.label}s yet`} text={`Create your first ${c.label} to start building your workspace.`}/>:<div className={`cards ${type==='documents'?'docs':''}`}>{items.map(x=><ResourceCard key={x._id} x={x} type={type} onEdit={()=>{setEdit(x);setOpen(true)}} onDelete={()=>setDel(x)}/>)}</div>}<ResourceModal type={type} open={open} onClose={()=>{setOpen(false);setEdit(null)}} initial={edit} onSave={save}/><Confirm open={!!del} onClose={()=>setDel(null)} onConfirm={remove}/></>}
function ResourceCard({x,type,onEdit,onDelete}){if(type==='plans')return <div className="card"><div className="card-top"><span className={`badge ${x.priority?.toLowerCase()}`}>{x.priority}</span><div><button className="icon-btn" onClick={onEdit}><Edit3 size={16}/></button><button className="icon-btn danger-icon" onClick={onDelete}><Trash2 size={16}/></button></div></div><h3>{x.title}</h3><p>{x.description||x.goal||'No description'}</p><div className="progress"><span style={{width:`${progress(x)}%`}}></span></div><div className="card-meta"><b>{progress(x)}%</b><span>{x.steps?.filter(s=>s.completed).length||0}/{x.steps?.length||0} steps</span></div></div>;if(type==='documents')return <div className="card"><div className="file-icon"><FileText/></div><div className="card-top"><span className="badge">{x.category}</span><div><button className="icon-btn" onClick={onEdit}><Edit3 size={16}/></button><button className="icon-btn danger-icon" onClick={onDelete}><Trash2 size={16}/></button></div></div><h3 className="truncate">{x.originalName}</h3><p>{x.description||'No description'}</p><div className="card-meta"><span>{formatBytes(x.size)}</span><button type="button" className="text-btn" onClick={() => downloadDocument(x)}><Download size={15}/> Download</button></div></div>;if(type==='ideas')return <div className="card"><div className="card-top"><span className="badge">{x.status}</span><button className="star" onClick={() => toggleFavorite(type, x)}><Star size={18} fill={x.favorite?'currentColor':'none'}/></button></div><h3>{x.title}</h3><p><b>Problem:</b> {x.problem||'Not defined yet'}</p><p><b>Next:</b> {x.nextStep||'Define next step'}</p><div className="card-meta"><span>{x.category||'General'}</span><div><button className="icon-btn" onClick={onEdit}><Edit3 size={16}/></button><button className="icon-btn danger-icon" onClick={onDelete}><Trash2 size={16}/></button></div></div></div>;return <div className="card"><div className="card-top"><span className="badge">{x.category}</span><button className="star" onClick={() => toggleFavorite(type, x)}><Star size={18} fill={x.favorite?'currentColor':'none'}/></button></div><h3>{x.name}</h3><a className="url" href={x.url} target="_blank" rel="noreferrer">{x.url} <ExternalLink size={14}/></a><p>{x.description||'No description'}</p><div className="card-meta"><span>{(x.tags||[]).join(' · ')}</span><div><button className="icon-btn" onClick={onEdit}><Edit3 size={16}/></button><button className="icon-btn danger-icon" onClick={onDelete}><Trash2 size={16}/></button></div></div></div>}
async function downloadDocument(x){
  try{
    const token=localStorage.getItem('pf_token');
    const r=await api.get(`/documents/${x._id}/download`,{responseType:'blob',headers:{Authorization:`Bearer ${token}`}});
    const url=URL.createObjectURL(r.data);
    const a=document.createElement('a');
    a.href=url;
    a.download=x.originalName||'document';
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }catch(e){toast.error(e.response?.data?.message||'Download failed')}
}
async function toggleFavorite(type,x){
  const endpoint=type==='ideas'?'/ideas':'/links';
  try{
    await api.put(`${endpoint}/${x._id}`,{favorite:!x.favorite});
    toast.success(!x.favorite?'Added to favorites':'Removed from favorites');
    window.dispatchEvent(new Event('pf-resource-refresh'));
  }catch(e){toast.error(e.response?.data?.message||'Update failed')}
}
function progress(x){return x.steps?.length?Math.round(x.steps.filter(s=>s.completed).length/x.steps.length*100):0}function formatBytes(n=0){if(!n)return '—';return `${(n/1024/1024).toFixed(1)} MB`}
function ResourceModal({type,open,onClose,initial,onSave}){const [f,setF]=useState({});useEffect(()=>{setF(initial?{...initial,tags:initial.tags?.join(', ')||'','steps':initial.steps||[]}: {})},[initial,open]);const set=(k,v)=>setF(x=>({...x,[k]:v}));if(type==='documents')return <Modal open={open} onClose={onClose} title={initial?'Edit document':'Upload document'}><form onSubmit={async e=>{e.preventDefault();if(initial)return onSave({description:f.description,category:f.category,tags:f.tags});const fd=new FormData();fd.append('file',f.file);fd.append('description',f.description||'');fd.append('category',f.category||'Other');fd.append('tags',f.tags||'');try{await api.post('/documents',fd,{headers:{'Content-Type':'multipart/form-data'}});toast.success('Uploaded');onClose();location.reload()}catch(e){toast.error(e.response?.data?.message||'Upload failed')}}}><Field label="File" type="file" required={!initial} onChange={e=>set('file',e.target.files[0])}/><Textarea label="Description" value={f.description||''} onChange={e=>set('description',e.target.value)}/><Select label="Category" value={f.category||'Other'} onChange={e=>set('category',e.target.value)}>{['Personal','Education','Work','Finance','Projects','Other'].map(x=><option key={x}>{x}</option>)}</Select><Field label="Tags (comma separated)" value={f.tags||''} onChange={e=>set('tags',e.target.value)}/><Button className="full">{initial?'Save changes':'Upload document'}</Button></form></Modal>;
return <Modal open={open} onClose={onClose} title={initial?`Edit ${type}`:`Create ${type}`}><form onSubmit={e=>{e.preventDefault();let d={...f};delete d._id;delete d.owner;delete d.createdAt;delete d.updatedAt;delete d.__v; if(type==='plans'){d.steps=(f.steps||[]).map(s=>({title:s.title,description:s.description,completed:s.completed,deadline:s.deadline}))}if(type==='links')d.tags=String(f.tags||'').split(',').map(s=>s.trim()).filter(Boolean);onSave(d)}}>{type==='plans'?<><Field label="Title" required value={f.title||''} onChange={e=>set('title',e.target.value)}/><Textarea label="Description" value={f.description||''} onChange={e=>set('description',e.target.value)}/><Textarea label="Goal" value={f.goal||''} onChange={e=>set('goal',e.target.value)}/><Select label="Priority" value={f.priority||'Medium'} onChange={e=>set('priority',e.target.value)}>{['Low','Medium','High'].map(x=><option key={x}>{x}</option>)}</Select><Field label="Deadline" type="date" value={f.deadline?String(f.deadline).slice(0,10):''} onChange={e=>set('deadline',e.target.value)}/><Textarea label="Notes" value={f.notes||''} onChange={e=>set('notes',e.target.value)}/><StepEditor steps={f.steps||[]} set={v=>set('steps',v)}/></>:type==='ideas'?<><Field label="Title" required value={f.title||''} onChange={e=>set('title',e.target.value)}/><Textarea label="Problem" value={f.problem||''} onChange={e=>set('problem',e.target.value)}/><Textarea label="Proposed solution" value={f.solution||''} onChange={e=>set('solution',e.target.value)}/><Field label="Target users" value={f.targetUsers||''} onChange={e=>set('targetUsers',e.target.value)}/><Field label="Required resources" value={f.resources||''} onChange={e=>set('resources',e.target.value)}/><Field label="Next step" value={f.nextStep||''} onChange={e=>set('nextStep',e.target.value)}/><Field label="Category" value={f.category||''} onChange={e=>set('category',e.target.value)}/><Select label="Status" value={f.status||'New'} onChange={e=>set('status',e.target.value)}>{['New','Exploring','Planned','Building','Completed'].map(x=><option key={x}>{x}</option>)}</Select><Textarea label="Notes" value={f.notes||''} onChange={e=>set('notes',e.target.value)}/></>:<><Field label="Website name" required value={f.name||''} onChange={e=>set('name',e.target.value)}/><Field label="URL" type="url" required value={f.url||''} onChange={e=>set('url',e.target.value)}/><Textarea label="Description" value={f.description||''} onChange={e=>set('description',e.target.value)}/><Select label="Category" value={f.category||'Other'} onChange={e=>set('category',e.target.value)}>{['Development','Education','AI','Design','Research','Work','Other'].map(x=><option key={x}>{x}</option>)}</Select><Field label="Tags (comma separated)" value={f.tags||''} onChange={e=>set('tags',e.target.value)}/></>}<Button className="full">Save</Button></form></Modal>}
function StepEditor({steps,set}){return <div className="step-editor"><div className="section-label">Steps</div>{steps.map((s,i)=><div className="step-input" key={i}><input value={s.title} placeholder={`Step ${i+1}`} onChange={e=>{const a=[...steps];a[i]={...a[i],title:e.target.value};set(a)}}/><button type="button" className="icon-btn" onClick={()=>set(steps.filter((_,j)=>j!==i))}><Trash2 size={15}/></button></div>)}<Button type="button" variant="ghost" onClick={()=>set([...steps,{title:'',completed:false}])}><Plus size={15}/> Add step</Button></div>}
